language: node_js
cache: yarn
node_js:
  - node
script:
  - yarn docs
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global github.token ${GITHUB_TOKEN}
  - git checkout master
  - git add README.md
  - 'git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git push
