title: Lane Configuration
introduction: |
features:
- feature: Two Lanes
  description: |
    Most residential streets.
  elements:
    - way
  osm:
    - '[lanes]=2'
  mapillary:
- feature: Multiple Lanes
  description: |
    Includes turning lanes
  elements:
    - way
  osm:
    - '[lanes]=5'
  mapillary:
- feature: Width
  description: |
    Most designated MUPs have a width of 3m,
    though some are wider. Walkways are typically 2m
  elements:
    - way
  osm:
    - '[width]=\*'
  mapillary:
- feature: Speed limit
  description: |
    Only show if the speed is posted different than 50.
  elements:
    - way
  osm:
    - '[maxspeed]=40'
  mapillary:
